Add support for `with open` in Python
In order to support `with open` syntax in Python, the methods
`__enter__` and `__exit__` must be defined. `__enter__` returns a
pointer to the object itself since the result variable from `with` is
called upon for operations such as `readline`

`__exit__` calls `Close` since it is the function that is invoked before
the `with` call is terminated

Note that the `boost::noncopyable` attribute was removed from the
`DsrcReadInMemory` definition because usage of it caused the following
error to be raised when using `with`:

TypeError: No to_python (by-value) converter found for C++ type:
dsrc::py::PyDsrcReadInMemory